
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app:  mongodb
    project:  roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetport: 27017
    name: web
  clusterIP: None
  selector:
    app:  mongodb
    project:  roboshop
    tier: db